D8 un 2444
dof-dss/Unity_svr_2 pull request #1056
Opened 2023-10-12 14:34 UTC by soda736

2023-10-13 09:15 UTC, omahm commented on project/sites/nicybersecuritycentre/themes/nicybersecuritycentre_theme/templates/layout/page--events.html.twig
> +  {% endif %}
Slight nitpick here. It'd be easier to read if this was aligned to its matching 'if' statement. I checked the number of if's versus endif just to check this wasn't a duplicate.

2023-10-13 09:16 UTC, omahm requested changes
Looks good. Just that stacked 'endif' that caught my attention.

2023-10-19 12:00 UTC, soda736 commented
Alot of changes since the last review. This still needs a bit of tweaking but may need merged in before the D10 upgrade on Unity 2 starts.

2023-10-19 12:03 UTC, DuttonMa approved these changes

2023-10-19 12:15 UTC, omahm approved these changes
LGTM

2023-10-19 12:28 UTC, closed without merging