initial config export - cvocni
dof-dss/Unity_svr_2 pull request #255
Opened 2022-11-01 16:03 UTC by AdamMcFet

2022-11-02 08:18 UTC, soda736 requested changes

2022-11-02 08:18 UTC, soda736 commented on .platform/routes.yaml
> +'https://www.cvocni/':
This should be cvocni.org?

2022-11-02 08:18 UTC, soda736 commented on .platform/routes.yaml
> +    to: 'https://www.cvocni/'
And here too cvocni.org?

2022-11-02 08:18 UTC, soda736 commented on project/project.yml
> +        url: cvocni
The site URL needs to be cvocni.org

2022-11-02 08:18 UTC, soda736 commented on project/config/cvocni/config/unity_internal_link_checker.linksettings.yml
> +site_url_list: "https://www.cvocni.org/\r\nhttps://cvocni.org/\r\nhttp://www.cvocni.org/\r\nhttp://cvocni.org/"
We don't need these URL's anymore as there is background code to add them all in. I need to update the new site documentation, sorry.

2022-11-02 17:38 UTC, DuttonMa approved these changes

2022-11-03 09:38 UTC, soda736 approved these changes

2022-11-03 09:39 UTC, merged